// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Foo.proto
// Protobuf C++ Version: 5.27.0-dev

#include "Foo.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace test {

inline constexpr Foo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : a_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        b_{0},
        c_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Foo::Foo(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FooDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FooDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FooDefaultTypeInternal() {}
  union {
    Foo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FooDefaultTypeInternal _Foo_default_instance_;
}  // namespace test
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Foo_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Foo_2eproto = nullptr;
const ::uint32_t
    TableStruct_Foo_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::test::Foo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::test::Foo, _impl_.a_),
        PROTOBUF_FIELD_OFFSET(::test::Foo, _impl_.b_),
        PROTOBUF_FIELD_OFFSET(::test::Foo, _impl_.c_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::test::Foo)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::test::_Foo_default_instance_._instance,
};
const char descriptor_table_protodef_Foo_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tFoo.proto\022\004test\"&\n\003Foo\022\t\n\001a\030\001 \001(\t\022\t\n\001b"
    "\030\002 \001(\005\022\t\n\001c\030\003 \001(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_Foo_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Foo_2eproto = {
    false,
    false,
    65,
    descriptor_table_protodef_Foo_2eproto,
    "Foo.proto",
    &descriptor_table_Foo_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_Foo_2eproto::offsets,
    file_level_enum_descriptors_Foo_2eproto,
    file_level_service_descriptors_Foo_2eproto,
};
namespace test {
// ===================================================================

class Foo::_Internal {
 public:
};

Foo::Foo(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:test.Foo)
}
inline PROTOBUF_NDEBUG_INLINE Foo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::test::Foo& from_msg)
      : a_(arena, from.a_),
        _cached_size_{0} {}

Foo::Foo(
    ::google::protobuf::Arena* arena,
    const Foo& from)
    : ::google::protobuf::Message(arena) {
  Foo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, b_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, b_),
           offsetof(Impl_, c_) -
               offsetof(Impl_, b_) +
               sizeof(Impl_::c_));

  // @@protoc_insertion_point(copy_constructor:test.Foo)
}
inline PROTOBUF_NDEBUG_INLINE Foo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : a_(arena),
        _cached_size_{0} {}

inline void Foo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, b_),
           0,
           offsetof(Impl_, c_) -
               offsetof(Impl_, b_) +
               sizeof(Impl_::c_));
}
Foo::~Foo() {
  // @@protoc_insertion_point(destructor:test.Foo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Foo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.a_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Foo::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Foo, _impl_._cached_size_),
              false,
          },
          &Foo::MergeImpl,
          &Foo::kDescriptorMethods,
          &descriptor_table_Foo_2eproto,
          nullptr,  // tracker
      };
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 18, 2> Foo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Foo_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::test::Foo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string a = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Foo, _impl_.a_)}},
    // int32 b = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Foo, _impl_.b_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Foo, _impl_.b_)}},
    // int32 c = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Foo, _impl_.c_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Foo, _impl_.c_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string a = 1;
    {PROTOBUF_FIELD_OFFSET(Foo, _impl_.a_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 b = 2;
    {PROTOBUF_FIELD_OFFSET(Foo, _impl_.b_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 c = 3;
    {PROTOBUF_FIELD_OFFSET(Foo, _impl_.c_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\10\1\0\0\0\0\0\0"
    "test.Foo"
    "a"
  }},
};

PROTOBUF_NOINLINE void Foo::Clear() {
// @@protoc_insertion_point(message_clear_start:test.Foo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_.ClearToEmpty();
  ::memset(&_impl_.b_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.c_) -
      reinterpret_cast<char*>(&_impl_.b_)) + sizeof(_impl_.c_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Foo::_InternalParse(const char* ptr,
                                        ::_pbi::ParseContext* ctx) {
  return ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
}

::uint8_t* Foo::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:test.Foo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string a = 1;
  if (!this->_internal_a().empty()) {
    const std::string& _s = this->_internal_a();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "test.Foo.a");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 b = 2;
  if (this->_internal_b() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_b(), target);
  }

  // int32 c = 3;
  if (this->_internal_c() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_c(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:test.Foo)
  return target;
}

::size_t Foo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:test.Foo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string a = 1;
  if (!this->_internal_a().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_a());
  }

  // int32 b = 2;
  if (this->_internal_b() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_b());
  }

  // int32 c = 3;
  if (this->_internal_c() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_c());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Foo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Foo*>(&to_msg);
  auto& from = static_cast<const Foo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:test.Foo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_a().empty()) {
    _this->_internal_set_a(from._internal_a());
  }
  if (from._internal_b() != 0) {
    _this->_impl_.b_ = from._impl_.b_;
  }
  if (from._internal_c() != 0) {
    _this->_impl_.c_ = from._impl_.c_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Foo::CopyFrom(const Foo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:test.Foo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Foo::IsInitialized() const {
  return true;
}

void Foo::InternalSwap(Foo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.a_, &other->_impl_.a_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Foo, _impl_.c_)
      + sizeof(Foo::_impl_.c_)
      - PROTOBUF_FIELD_OFFSET(Foo, _impl_.b_)>(
          reinterpret_cast<char*>(&_impl_.b_),
          reinterpret_cast<char*>(&other->_impl_.b_));
}

::google::protobuf::Metadata Foo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace test
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Foo_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
